"""add submission contact action fields

Revision ID: 08f666a09984
Revises: 4e280f2af0c9
Create Date: 2026-09-09 12:59:15.770908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f666a09984'
down_revision = '4e280f2af0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('directions_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ticket_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_column('ticket_url')
        batch_op.drop_column('directions_url')
        batch_op.drop_column('whatsapp_number')

    # ### end Alembic commands ###
