"""add category image url

Revision ID: 112ae3d84919
Revises: 7c22f1b6c881
Create Date: 2026-09-04 09:54:29.393578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112ae3d84919'
down_revision = '7c22f1b6c881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
