"""Add push subscribers table

Revision ID: 1171f0430646
Revises: 1a0414e3a980
Create Date: 2026-09-02 02:53:52.632951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1171f0430646'
down_revision = '1a0414e3a980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscribers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscribers_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscribers_zone_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscribers_active'))

    op.drop_table('push_subscribers')
    # ### end Alembic commands ###
