"""add reminder processing timestamp

Revision ID: 20d76c8bcd9b
Revises: b15b042c98a1
Create Date: 2026-09-11 08:14:13.631650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d76c8bcd9b'
down_revision = 'b15b042c98a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_started_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_reminders_processing_started_at'), ['processing_started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_reminders_processing_started_at'))
        batch_op.drop_column('processing_started_at')

    # ### end Alembic commands ###
