"""initial LAC PostgreSQL schema

Revision ID: 28fc479223eb
Revises: 
Create Date: 2026-08-26 12:30:21.661866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fc479223eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('qr_type', sa.String(length=30), nullable=True),
    sa.Column('default_category', sa.String(length=50), nullable=True),
    sa.Column('partner_name', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('venue', sa.String(length=150), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('publish_from', sa.Date(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('category_selected', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_scans_scanned_at'), ['scanned_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_scans_scanned_at'))

    op.drop_table('qr_scans')
    op.drop_table('content_items')
    op.drop_table('access_points')
    op.drop_table('zones')
    # ### end Alembic commands ###
