"""add category slideshow images

Revision ID: 40017556407c
Revises: 112ae3d84919
Create Date: 2026-09-05 07:32:10.716873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40017556407c'
down_revision = '112ae3d84919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url_3', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_url_3')
        batch_op.drop_column('image_url_2')

    # ### end Alembic commands ###
