"""add submission images and tracking code

Revision ID: 4afe10e4d003
Revises: 678d33f118cd
Create Date: 2026-08-27 08:02:55.491146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afe10e4d003'
down_revision = '678d33f118cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_submission_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['pending_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_submission_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_submission_images_submission_id'), ['submission_id'], unique=False)

    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_code', sa.String(length=40), nullable=False))
        batch_op.create_index(batch_op.f('ix_pending_submissions_tracking_code'), ['tracking_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_submissions_tracking_code'))
        batch_op.drop_column('tracking_code')

    with op.batch_alter_table('pending_submission_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_submission_images_submission_id'))

    op.drop_table('pending_submission_images')
    # ### end Alembic commands ###
