"""add ticket url to content items

Revision ID: 4e280f2af0c9
Revises: 874c41465eef
Create Date: 2026-09-09 11:58:02.200030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e280f2af0c9'
down_revision = '874c41465eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('ticket_url')

    # ### end Alembic commands ###
