"""Add push notification history

Revision ID: 4f0138f97dac
Revises: 1171f0430646
Create Date: 2026-09-02 05:26:35.217018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0138f97dac'
down_revision = '1171f0430646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_subscribers', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_notifications_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_notifications_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_notifications_zone_id'))
        batch_op.drop_index(batch_op.f('ix_push_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_push_notifications_content_item_id'))

    op.drop_table('push_notifications')
    # ### end Alembic commands ###
