"""add content reminders

Revision ID: 55e60c6ea4ef
Revises: 701bfbe7c384
Create Date: 2026-09-10 08:12:55.912026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e60c6ea4ef'
down_revision = '701bfbe7c384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('access_point_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=30), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_reminders_access_point_id'), ['access_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_reminder_type'), ['reminder_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_reminders_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_reminders_zone_id'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_reminder_type'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_created_at'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_content_reminders_access_point_id'))

    op.drop_table('content_reminders')
    # ### end Alembic commands ###
