"""add content images

Revision ID: 678d33f118cd
Revises: cf02350cea14
Create Date: 2026-08-27 01:52:01.861530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678d33f118cd'
down_revision = 'cf02350cea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_images_content_item_id'), ['content_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_images_content_item_id'))

    op.drop_table('content_images')
    # ### end Alembic commands ###
