"""add zone under pushnoti

Revision ID: 6d5e788b3fbb
Revises: beb6ba176d0a
Create Date: 2026-09-12 17:44:34.168546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5e788b3fbb'
down_revision = 'beb6ba176d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_push_notification_content_item'), type_='unique')
        batch_op.create_unique_constraint('uq_push_notification_content_zone', ['content_item_id', 'zone_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_push_notification_content_zone', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_push_notification_content_item'), ['content_item_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
