"""add submission campaign times

Revision ID: 701bfbe7c384
Revises: b4e90580fdeb
Create Date: 2026-09-10 05:24:47.440463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701bfbe7c384'
down_revision = 'b4e90580fdeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
