"""Add push subscriber category preferences

Revision ID: 7c22f1b6c881
Revises: 821cec56dbe2
Create Date: 2026-09-03 09:51:13.736577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c22f1b6c881'
down_revision = '821cec56dbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriber_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['push_subscribers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'category', name='uq_push_subscriber_category')
    )
    with op.batch_alter_table('push_subscriber_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriber_preferences_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriber_preferences_subscriber_id'), ['subscriber_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriber_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriber_preferences_subscriber_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriber_preferences_category'))

    op.drop_table('push_subscriber_preferences')
    # ### end Alembic commands ###
