"""Add engagement event tracking

Revision ID: 821cec56dbe2
Revises: ab81b71708a5
Create Date: 2026-09-02 07:55:09.657754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821cec56dbe2'
down_revision = 'ab81b71708a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('access_point_id', sa.Integer(), nullable=True),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_events_access_point_id'), ['access_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_events_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagement_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_events_zone_id'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_content_item_id'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_category'))
        batch_op.drop_index(batch_op.f('ix_engagement_events_access_point_id'))

    op.drop_table('engagement_events')
    # ### end Alembic commands ###
