"""add yoco payment tracking

Revision ID: 874c41465eef
Revises: 1b835ce34501
Create Date: 2026-09-08 10:09:21.928131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874c41465eef'
down_revision = '1b835ce34501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yoco_checkout_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('yoco_payment_id', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_pending_submissions_yoco_checkout_id'), ['yoco_checkout_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pending_submissions_yoco_payment_id'), ['yoco_payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_submissions_yoco_payment_id'))
        batch_op.drop_index(batch_op.f('ix_pending_submissions_yoco_checkout_id'))
        batch_op.drop_column('yoco_payment_id')
        batch_op.drop_column('yoco_checkout_id')

    # ### end Alembic commands ###
