"""add ambassador content permission

Revision ID: 99d294d3738c
Revises: 3c26cb989ff3
Create Date: 2026-10-04 10:31:34.074954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d294d3738c'
down_revision = '3c26cb989ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_ambassadors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add_content', sa.Boolean(), nullable=False))

    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_push_notification_content_zone'), type_='unique')
        batch_op.create_unique_constraint('uq_push_notification_content_item', ['content_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_push_notification_content_item', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_push_notification_content_zone'), ['content_item_id', 'zone_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('community_ambassadors', schema=None) as batch_op:
        batch_op.drop_column('can_add_content')

    # ### end Alembic commands ###
