"""add content lifecycle fields

Revision ID: a652edc891f9
Revises: e5ea8befbfbb
Create Date: 2026-09-01 01:55:30.119585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a652edc891f9'
down_revision = 'e5ea8befbfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for existing rows ###

    with op.batch_alter_table(
        "content_items",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "content_type",
                sa.String(length=60),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "lifetime_type",
                sa.String(length=30),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "availability_status",
                sa.String(length=30),
                nullable=False,
                server_default="available",
            )
        )

        batch_op.add_column(
            sa.Column(
                "notification_eligible",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

        batch_op.create_index(
            batch_op.f(
                "ix_content_items_availability_status"
            ),
            ["availability_status"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_content_items_content_type"
            ),
            ["content_type"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_content_items_lifetime_type"
            ),
            ["lifetime_type"],
            unique=False,
        )


    with op.batch_alter_table(
        "pending_submissions",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "content_type",
                sa.String(length=60),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "lifetime_type",
                sa.String(length=30),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "availability_status",
                sa.String(length=30),
                nullable=False,
                server_default="available",
            )
        )

        batch_op.add_column(
            sa.Column(
                "notification_eligible",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

        batch_op.create_index(
            batch_op.f(
                "ix_pending_submissions_availability_status"
            ),
            ["availability_status"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_pending_submissions_content_type"
            ),
            ["content_type"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_pending_submissions_lifetime_type"
            ),
            ["lifetime_type"],
            unique=False,
        )

    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_submissions_lifetime_type'))
        batch_op.drop_index(batch_op.f('ix_pending_submissions_content_type'))
        batch_op.drop_index(batch_op.f('ix_pending_submissions_availability_status'))
        batch_op.drop_column('notification_eligible')
        batch_op.drop_column('availability_status')
        batch_op.drop_column('lifetime_type')
        batch_op.drop_column('content_type')

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_lifetime_type'))
        batch_op.drop_index(batch_op.f('ix_content_items_content_type'))
        batch_op.drop_index(batch_op.f('ix_content_items_availability_status'))
        batch_op.drop_column('notification_eligible')
        batch_op.drop_column('availability_status')
        batch_op.drop_column('lifetime_type')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
