"""Prevent duplicate content notifications

Revision ID: ab81b71708a5
Revises: 4f0138f97dac
Create Date: 2026-09-02 06:00:42.959522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab81b71708a5'
down_revision = '4f0138f97dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_push_notification_content_item', ['content_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_push_notification_content_item', type_='unique')

    # ### end Alembic commands ###
