"""link reminders to push subscribers

Revision ID: b15b042c98a1
Revises: 55e60c6ea4ef
Create Date: 2026-09-10 12:21:45.517784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15b042c98a1'
down_revision = '55e60c6ea4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscriber_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_reminders_push_subscriber_id'), ['push_subscriber_id'], unique=False)
        batch_op.create_foreign_key(None, 'push_subscribers', ['push_subscriber_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_content_reminders_push_subscriber_id'))
        batch_op.drop_column('push_subscriber_id')

    # ### end Alembic commands ###
