"""add sponsored pricing fields

Revision ID: b5e8fe825abe
Revises: 690062d68f6e
Create Date: 2026-09-12 03:28:14.007033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e8fe825abe'
down_revision = '690062d68f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsored_duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sponsorship_amount_due', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('sponsorship_amount_due')
        batch_op.drop_column('sponsored_duration_days')

    # ### end Alembic commands ###
