"""add organizer ownership

Revision ID: beb6ba176d0a
Revises: b5e8fe825abe
Create Date: 2026-09-12 14:54:14.647480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb6ba176d0a'
down_revision = 'b5e8fe825abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizers_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizers_phone'), ['phone'], unique=True)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_content_items_organizer_id'), ['organizer_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizers', ['organizer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pending_submissions_organizer_id'), ['organizer_id'], unique=False)
        batch_op.create_foreign_key(None, 'organizers', ['organizer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pending_submissions_organizer_id'))
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_content_items_organizer_id'))
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizers_phone'))
        batch_op.drop_index(batch_op.f('ix_organizers_email'))
        batch_op.drop_index(batch_op.f('ix_organizers_active'))

    op.drop_table('organizers')
    # ### end Alembic commands ###
