"""link submissions to published content

Revision ID: d8d8c16cf7a9
Revises: 4afe10e4d003
Create Date: 2026-08-27 10:01:10.558343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d8c16cf7a9'
down_revision = '4afe10e4d003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_content_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'content_items', ['published_content_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('published_content_id')

    # ### end Alembic commands ###
