"""add listing view count

Revision ID: e5ea8befbfbb
Revises: d8d8c16cf7a9
Create Date: 2026-08-27 15:47:01.566894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ea8befbfbb'
down_revision = 'd8d8c16cf7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table(
       "content_items",
       schema=None,
    ) as batch_op:

       batch_op.add_column(
        sa.Column(
            "view_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        )
       )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
