"""add listing levels and ownership

Revision ID: e71720a65148
Revises: f5ba1ecb94ec
Create Date: 2026-09-06 14:59:45.443750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71720a65148'
down_revision = 'f5ba1ecb94ec'
branch_labels = None
depends_on = None

def upgrade():
    # ---------------------------------------------------------
    # 1. Add columns as nullable first.
    #
    # Existing ContentItem rows already exist, so PostgreSQL
    # needs the columns to temporarily allow NULL values.
    # ---------------------------------------------------------

    with op.batch_alter_table(
        "content_items",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "listing_level",
                sa.String(length=30),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "ownership_status",
                sa.String(length=30),
                nullable=True,
            )
        )

        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                nullable=True,
            )
        )


    # ---------------------------------------------------------
    # 2. Backfill all EXISTING Kalxa listings.
    #
    # Existing content becomes:
    #
    # Level 1 — Discovery
    # Unclaimed
    # Not verified
    # ---------------------------------------------------------

    op.execute(
        """
        UPDATE content_items
        SET listing_level = 'discovery'
        WHERE listing_level IS NULL
        """
    )

    op.execute(
        """
        UPDATE content_items
        SET ownership_status = 'unclaimed'
        WHERE ownership_status IS NULL
        """
    )

    op.execute(
        """
        UPDATE content_items
        SET is_verified = FALSE
        WHERE is_verified IS NULL
        """
    )


    # ---------------------------------------------------------
    # 3. Now make the columns required.
    #
    # At this point no existing row contains NULL.
    # ---------------------------------------------------------

    with op.batch_alter_table(
        "content_items",
        schema=None,
    ) as batch_op:

        batch_op.alter_column(
            "listing_level",
            existing_type=sa.String(length=30),
            nullable=False,
        )

        batch_op.alter_column(
            "ownership_status",
            existing_type=sa.String(length=30),
            nullable=False,
        )

        batch_op.alter_column(
            "is_verified",
            existing_type=sa.Boolean(),
            nullable=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_content_items_listing_level"
            ),
            ["listing_level"],
            unique=False,
        )

        batch_op.create_index(
            batch_op.f(
                "ix_content_items_ownership_status"
            ),
            ["ownership_status"],
            unique=False,
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_ownership_status'))
        batch_op.drop_index(batch_op.f('ix_content_items_listing_level'))
        batch_op.drop_column('image_url_3')
        batch_op.drop_column('image_url_2')
        batch_op.drop_column('special_offer')
        batch_op.drop_column('menu_highlights')
        batch_op.drop_column('directions_url')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('ownership_status')
        batch_op.drop_column('listing_level')

    # ### end Alembic commands ###
