"""add listing claims

Revision ID: f57dde65cd0c
Revises: e71720a65148
Create Date: 2026-09-06 16:31:02.176087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57dde65cd0c'
down_revision = 'e71720a65148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('claimant_name', sa.String(length=120), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('proof_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_claims_content_item_id'), ['content_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_claims_status'), ['status'], unique=False)

    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_hours', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('directions_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('menu_highlights', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_offer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url_3', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('image_url_3')
        batch_op.drop_column('image_url_2')
        batch_op.drop_column('special_offer')
        batch_op.drop_column('menu_highlights')
        batch_op.drop_column('directions_url')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('opening_hours')

    with op.batch_alter_table('listing_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_claims_status'))
        batch_op.drop_index(batch_op.f('ix_listing_claims_content_item_id'))

    op.drop_table('listing_claims')
    # ### end Alembic commands ###
