"""add zone category appearances

Revision ID: f5ba1ecb94ec
Revises: 40017556407c
Create Date: 2026-09-05 14:15:55.166172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ba1ecb94ec'
down_revision = '40017556407c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_category_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_url_2', sa.String(length=500), nullable=True),
    sa.Column('image_url_3', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'category_id', name='uq_zone_category_appearance')
    )
    with op.batch_alter_table('zone_category_appearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_category_appearances_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_category_appearances_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_category_appearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_category_appearances_zone_id'))
        batch_op.drop_index(batch_op.f('ix_zone_category_appearances_category_id'))

    op.drop_table('zone_category_appearances')
    # ### end Alembic commands ###
