"""add archived fields to content items

Revision ID: e42e72952a6f
Revises: 
Create Date: 2026-08-26 07:19:16.090283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42e72952a6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table(
        "content_items",
        schema=None,
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                "archived",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

        batch_op.add_column(
            sa.Column(
                "archived_at",
                sa.DateTime(),
                nullable=True,
            )
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
